

services:
  rip_jobs_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: rip_jobs_image:latest
    container_name: rip_jobs_container
    volumes:
      - ./data:/app/data
      - ./src/content:/app/src/content       # Bill's local test path
      #- ../../src/content:/app/src/content  # Shashank's prod path
    
    command: ["python", "rip_jobs.py", "--sections", "css-oxhdrx", "--job_blocks", "css-aapqz6", "--job_desc_len", "350"]
    # Uncomment below if you want to keep the container running
    # tty: true
    # stdin_open: true
